#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Voxel-difference analysis for fixed-lattice voxelized densities.

Updates:
- Reads voxel_size (Å) from meta.json generated by dataset pipeline
- Sets scaling_factor = 1 always (fixed lattice → no per-structure scaling)
- Creates CCP4 maps with correct voxel spacing
- Includes plot_losses()
"""

import os
import sys
import json
import re
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from scipy.stats import pearsonr
from density_manipulation import create_ccp4_map_  # must exist


# ───────────────────────────────
# Minimal VAE wrapper
# ───────────────────────────────
class VAE(tf.keras.Model):
    def __init__(self, latent_dim, encoder, decoder):
        super(VAE, self).__init__()
        self.latent_dim = latent_dim
        self.encoder = encoder
        self.decoder = decoder

    def encode(self, x):
        mean, logvar = tf.split(self.encoder(x), 2, axis=1)
        return mean, logvar

    def decode(self, z):
        return self.decoder(z)


# ───────────────────────────────
# TFRecord utilities
# ───────────────────────────────
def load_tfrecord_dataset(tfrecord_path, batch_size=16, shuffle=False):
    feature_description = {
        'data': tf.io.FixedLenFeature([52*52*52], tf.float32)
    }

    def _parse(example):
        parsed = tf.io.parse_single_example(example, feature_description)
        vol = tf.reshape(parsed['data'], (52,52,52,1))
        return vol

    ds = tf.data.TFRecordDataset(tfrecord_path)
    ds = ds.map(_parse)
    if shuffle:
        ds = ds.shuffle(1000)
    ds = ds.batch(batch_size)
    return ds


# ───────────────────────────────
# Latent PCA
# ───────────────────────────────
def plot_latent_pca(vae, tfrecord_path, save_path, batch_size=16):
    dataset = load_tfrecord_dataset(tfrecord_path, batch_size=batch_size)
    z_all = []

    for batch in dataset:
        mean, _ = vae.encode(batch)
        z_all.append(mean.numpy())

    z = np.concatenate(z_all, axis=0)

    os.makedirs(save_path, exist_ok=True)
    latent_mean = np.mean(z, axis=0)
    latent_std = np.std(z, axis=0)
    latent_max = np.max(z, axis=0)
    latent_min = np.min(z, axis=0)


    np.savetxt(
        os.path.join(save_path, "latent_stats.txt"),
        np.vstack((latent_mean, latent_std,latent_min,latent_max)).T,
        header="mean std", fmt="%.6f"
    )

    pca = PCA(n_components=2)
    z_p = pca.fit_transform(z)

    plt.figure(figsize=(8,6))
    plt.scatter(z_p[:,0], z_p[:,1], alpha=0.5)
    plt.xlabel("PC1")
    plt.ylabel("PC2")
    plt.title("Latent PCA")
    plt.savefig(os.path.join(save_path, "latent_pca.png"), dpi=300)
    plt.close()

    print(f"Saved latent PCA to {save_path}/latent_pca.png")


# ───────────────────────────────
# CLI
# ───────────────────────────────
if __name__ == "__main__":
    model_dir = sys.argv[1]
    tfrecord_path = sys.argv[2]
    save_dir = sys.argv[3]

    # Restore VAE
    encoder = tf.keras.models.load_model(os.path.join(model_dir,"encoder_model.keras"))
    decoder = tf.keras.models.load_model(os.path.join(model_dir,"decoder_model.keras"))
    latent_dim = encoder.output_shape[-1] // 2
    vae = VAE(latent_dim, encoder, decoder)

    print("Plotting Latent PCA…")
    plot_latent_pca(vae, tfrecord_path, save_dir)

    #print("Plotting losses…")
    #plot_losses(model_dir)


